In [1]:
import pandas as pd

In [2]:
pd.__version__

'3.0.5'

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv")

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [5]:
df.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,10000.000000,10000.00000,10000.000000,10000.000000,9123.000000,10000.000000,9736.000000,10000.000000
mean,1999.549500,3.50400,2268.807000,6.035200,254.446016,4286.754000,18.888044,29.997700
std,14.207925,0.95209,183.447355,0.542578,22.844613,266.212491,1.279543,2.930245
min,1975.000000,2.00000,1590.000000,4.000000,171.000000,3320.000000,14.000000,19.800000
25%,1987.000000,3.00000,2150.000000,6.000000,239.000000,4110.000000,18.000000,28.000000
50%,2000.000000,4.00000,2270.000000,6.000000,254.000000,4280.000000,18.900000,30.000000
75%,2012.000000,4.00000,2390.000000,6.000000,270.000000,4470.000000,19.700000,31.900000
max,2024.000000,5.00000,3110.000000,8.000000,334.000000,5460.000000,23.800000,41.200000

In [6]:
df.shape

(10000, 11)

In [7]:
unique_fuel_type = df.fuel_type.unique()
len(unique_fuel_type)

3

In [8]:
cols = df.columns
count = 0
for col in cols:
    if df[col].isna().sum() > 0:
        count += 1
print(count)

2

In [9]:
df_asia = df[df['origin']=='Asia']
df_asia.describe()

,model_year,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
count,2994.000000,2994.000000,2994.000000,2994.000000,2729.000000,2994.000000,2994.000000,2994.000000
mean,1999.436540,3.498664,2252.448230,5.998998,247.662514,4235.003340,18.897829,30.741015
std,14.251106,0.950582,184.008122,0.552308,21.321483,263.520367,1.315201,2.835474
min,1975.000000,2.000000,1590.000000,4.000000,174.000000,3320.000000,14.400000,21.300000
25%,1987.000000,3.000000,2130.000000,6.000000,234.000000,4060.000000,18.000000,28.700000
50%,1999.000000,4.000000,2260.000000,6.000000,248.000000,4230.000000,18.900000,30.700000
75%,2012.000000,4.000000,2370.000000,6.000000,262.000000,4410.000000,19.800000,32.500000
max,2024.000000,5.000000,3020.000000,8.000000,334.000000,5280.000000,23.800000,41.200000

In [10]:
median_hp = df['horsepower'].median()
most_freq_hp = df['horsepower'].mode()
df_mod = df.copy()
df_mod['horsepower'] = df_mod['horsepower'].fillna(most_freq_hp)
new_median_hp = df_mod['horsepower'].median()
print(f"new median: {new_median_hp}, old median: {median_hp}")

new median: 254.0, old median: 254.0

In [16]:
import numpy as np
asia_vehicle = df_asia[['vehicle_weight', 'model_year']][:7]
X = np.array(asia_vehicle)
print(X)

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]

In [18]:
XTX = np.matmul(X.T, X)
print(XTX)

[[131950500  60750580]
 [ 60750580  28041424]]

In [26]:
XTX_inv = np.linalg.inv(XTX)
XTX_inv

array([[ 2.96830537e-06, -6.43071025e-06],
       [-6.43071025e-06,  1.39675281e-05]])

In [27]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

In [28]:
w = (XTX_inv @ X.T) @ y
w

array([0.13644777, 0.2327492 ])

In [30]:
sum_w = w.sum()
print(f"sum = {sum_w}")

sum = 0.36919696904925486