### Previous Code

In [1]:
import pandas as pd

df = pd.read_csv("course_lead_scoring_2026.csv")
df.head()

,lead_source,industry,employment_status,location,annual_income,number_of_courses_viewed,interaction_count,lead_score,converted
0,organic_search,technology,employed,europe,88160.0,3,4,0.64,1
1,social_media,technology,employed,south_america,72688.0,3,7,0.72,1
2,referral,retail,employed,europe,44697.0,3,4,0.58,1
3,paid_ads,manufacturing,student,NaN,NaN,3,6,0.57,0
4,referral,manufacturing,student,north_america,24062.0,4,5,0.62,1

In [2]:
for col in df.columns:
  if df[col].dtype == 'str':
    df[col] = df[col].fillna('NA')
  else:
    df[col] = df[col].fillna(0.0)

In [3]:
from sklearn.model_selection import train_test_split

df_full_train, df_test = train_test_split(df, test_size=0.2, random_state=1)
df_train, df_val = train_test_split(
    df_full_train, test_size=0.25, random_state=1
)
print(f"train data: {df_train.shape}")
print(f"val data: {df_val.shape}")
print(f"test data: {df_test.shape}")

train data: (3000, 9)
val data: (1000, 9)
test data: (1000, 9)

In [4]:
numeric_cols = df.select_dtypes(include='number')
catagorical_cols = df.select_dtypes(include='object')

/tmp/ipykernel_1010/2700427808.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  catagorical_cols = df.select_dtypes(include='object')

In [5]:
from sklearn.feature_extraction import DictVectorizer

data_dict = df_train.to_dict(orient='records')
vec = DictVectorizer(sparse=False)
encoded_train_data = vec.fit_transform(data_dict)
encoded_df_train = pd.DataFrame(
    encoded_train_data, columns=vec.get_feature_names_out())
encoded_df_train.head()

,annual_income,converted,employment_status=NA,employment_status=employed,employment_status=self_employed,employment_status=student,employment_status=unemployed,industry=NA,industry=education,industry=finance,...,lead_source=paid_ads,lead_source=referral,lead_source=social_media,location=NA,location=africa,location=asia,location=europe,location=north_america,location=south_america,number_of_courses_viewed
0,80198.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,5.0
1,50548.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0
2,76300.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
3,80371.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2.0
4,73567.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,2.0

In [6]:
y_train = encoded_df_train.pop('converted')
X_train = encoded_df_train
print(f"X shape: {X_train.shape}, y shape: {y_train.shape}")

X shape: (3000, 28), y shape: (3000,)

In [7]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [8]:
val_dict = df_val.to_dict(orient='records')
encoded_val_data = vec.transform(val_dict)
encoded_df_val = pd.DataFrame(
    encoded_val_data, columns=vec.get_feature_names_out())
encoded_df_val.head()

,annual_income,converted,employment_status=NA,employment_status=employed,employment_status=self_employed,employment_status=student,employment_status=unemployed,industry=NA,industry=education,industry=finance,...,lead_source=paid_ads,lead_source=referral,lead_source=social_media,location=NA,location=africa,location=asia,location=europe,location=north_america,location=south_america,number_of_courses_viewed
0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0
1,63357.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,4.0
2,72351.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0
3,41501.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0
4,44817.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,3.0

In [9]:
y_val = encoded_df_val.pop('converted')
X_val = encoded_df_val

print(f"X shape: {X_val.shape}, y shape: {y_val.shape}")

X shape: (1000, 28), y shape: (1000,)

In [10]:
from sklearn.metrics import roc_auc_score

y_pred = model.predict(X_val)
score = roc_auc_score(y_val, y_pred)
print(f"auc score: {round(score, 3)}")

auc score: 0.598

In [11]:
import numpy as np
from sklearn.metrics import precision_score, recall_score, precision_recall_curve

thresholds = [t/100 for t in range(0, 100)]
prob = model.predict_proba(X_val)
pred_prob = prob[:, 1]
scores = {}
precisions = []
recalls = []

for t in thresholds:
  y_pred = (pred_prob >= t).astype(float)
  precision = precision_score(y_val, y_pred, zero_division=0)
  recall = recall_score(y_val, y_pred, zero_division=0)
  scores[t] = {"precision": precision, "recall": recall}
  precisions.append(precision)
  recalls.append(recall)

print(scores)

{0.0: {'precision': 0.586, 'recall': 1.0}, 0.01: {'precision': 0.586, 'recall': 1.0}, 0.02: {'precision': 0.586, 'recall': 1.0}, 0.03: {'precision': 0.586, 'recall': 1.0}, 0.04: {'precision': 0.586, 'recall': 1.0}, 0.05: {'precision': 0.586, 'recall': 1.0}, 0.06: {'precision': 0.586, 'recall': 1.0}, 0.07: {'precision': 0.586, 'recall': 1.0}, 0.08: {'precision': 0.586, 'recall': 1.0}, 0.09: {'precision': 0.586, 'recall': 1.0}, 0.1: {'precision': 0.586, 'recall': 1.0}, 0.11: {'precision': 0.586, 'recall': 1.0}, 0.12: {'precision': 0.586, 'recall': 1.0}, 0.13: {'precision': 0.586, 'recall': 1.0}, 0.14: {'precision': 0.586, 'recall': 1.0}, 0.15: {'precision': 0.586, 'recall': 1.0}, 0.16: {'precision': 0.586, 'recall': 1.0}, 0.17: {'precision': 0.586, 'recall': 1.0}, 0.18: {'precision': 0.586, 'recall': 1.0}, 0.19: {'precision': 0.586, 'recall': 1.0}, 0.2: {'precision': 0.586, 'recall': 1.0}, 0.21: {'precision': 0.586, 'recall': 1.0}, 0.22: {'precision': 0.586, 'recall': 1.0}, 0.23: {'precision': 0.586, 'recall': 1.0}, 0.24: {'precision': 0.586, 'recall': 1.0}, 0.25: {'precision': 0.586, 'recall': 1.0}, 0.26: {'precision': 0.5865865865865866, 'recall': 1.0}, 0.27: {'precision': 0.5877632898696088, 'recall': 1.0}, 0.28: {'precision': 0.591321897073663, 'recall': 1.0}, 0.29: {'precision': 0.591321897073663, 'recall': 1.0}, 0.3: {'precision': 0.5925176946410515, 'recall': 1.0}, 0.31: {'precision': 0.5963302752293578, 'recall': 0.9982935153583617}, 0.32: {'precision': 0.5961145194274029, 'recall': 0.9948805460750854}, 0.33: {'precision': 0.5973360655737705, 'recall': 0.9948805460750854}, 0.34: {'precision': 0.6016511867905057, 'recall': 0.9948805460750854}, 0.35: {'precision': 0.6028955532574974, 'recall': 0.9948805460750854}, 0.36: {'precision': 0.6047717842323651, 'recall': 0.9948805460750854}, 0.37: {'precision': 0.6069182389937107, 'recall': 0.9880546075085325}, 0.38: {'precision': 0.6073684210526316, 'recall': 0.984641638225256}, 0.39: {'precision': 0.6095238095238096, 'recall': 0.9829351535836177}, 0.4: {'precision': 0.6128342245989304, 'recall': 0.9778156996587031}, 0.41: {'precision': 0.6190476190476191, 'recall': 0.9761092150170648}, 0.42: {'precision': 0.6200873362445415, 'recall': 0.9692832764505119}, 0.43: {'precision': 0.6225165562913907, 'recall': 0.962457337883959}, 0.44: {'precision': 0.623608017817372, 'recall': 0.9556313993174061}, 0.45: {'precision': 0.6281179138321995, 'recall': 0.9453924914675768}, 0.46: {'precision': 0.6320645905420992, 'recall': 0.9351535836177475}, 0.47: {'precision': 0.6343457943925234, 'recall': 0.9266211604095563}, 0.48: {'precision': 0.6382978723404256, 'recall': 0.9215017064846417}, 0.49: {'precision': 0.6399521531100478, 'recall': 0.9129692832764505}, 0.5: {'precision': 0.6436363636363637, 'recall': 0.9061433447098977}, 0.51: {'precision': 0.6467661691542289, 'recall': 0.8873720136518771}, 0.52: {'precision': 0.6494325346784363, 'recall': 0.878839590443686}, 0.53: {'precision': 0.6580310880829016, 'recall': 0.8668941979522184}, 0.54: {'precision': 0.6618229854689565, 'recall': 0.8549488054607508}, 0.55: {'precision': 0.6675712347354138, 'recall': 0.8395904436860068}, 0.56: {'precision': 0.675, 'recall': 0.8293515358361775}, 0.57: {'precision': 0.6789772727272727, 'recall': 0.8156996587030717}, 0.58: {'precision': 0.6896046852122987, 'recall': 0.8037542662116041}, 0.59: {'precision': 0.6956521739130435, 'recall': 0.7918088737201365}, 0.6: {'precision': 0.7063369397217929, 'recall': 0.7798634812286689}, 0.61: {'precision': 0.719047619047619, 'recall': 0.773037542662116}, 0.62: {'precision': 0.7259136212624585, 'recall': 0.7457337883959044}, 0.63: {'precision': 0.7327586206896551, 'recall': 0.7252559726962458}, 0.64: {'precision': 0.7298747763864043, 'recall': 0.6962457337883959}, 0.65: {'precision': 0.7410207939508506, 'recall': 0.6689419795221843}, 0.66: {'precision': 0.748015873015873, 'recall': 0.643344709897611}, 0.67: {'precision': 0.7578288100208769, 'recall': 0.6194539249146758}, 0.68: {'precision': 0.7682119205298014, 'recall': 0.5938566552901023}, 0.69: {'precision': 0.7756563245823389, 'recall': 0.5546075085324232}, 0.7: {'precision': 0.7913486005089059, 'recall': 0.5307167235494881}, 0.71: {'precision': 0.8060941828254847, 'recall': 0.49658703071672355}, 0.72: {'precision': 0.8176470588235294, 'recall': 0.47440273037542663}, 0.73: {'precision': 0.8233438485804416, 'recall': 0.4453924914675768}, 0.74: {'precision': 0.8339100346020761, 'recall': 0.4112627986348123}, 0.75: {'precision': 0.8384615384615385, 'recall': 0.3720136518771331}, 0.76: {'precision': 0.8464730290456431, 'recall': 0.34812286689419797}, 0.77: {'precision': 0.8545454545454545, 'recall': 0.32081911262798635}, 0.78: {'precision': 0.8627450980392157, 'recall': 0.3003412969283277}, 0.79: {'precision': 0.8548387096774194, 'recall': 0.2713310580204778}, 0.8: {'precision': 0.8580246913580247, 'recall': 0.23720136518771331}, 0.81: {'precision': 0.8611111111111112, 'recall': 0.21160409556313994}, 0.82: {'precision': 0.873015873015873, 'recall': 0.18771331058020477}, 0.83: {'precision': 0.8796296296296297, 'recall': 0.1621160409556314}, 0.84: {'precision': 0.8977272727272727, 'recall': 0.1348122866894198}, 0.85: {'precision': 0.8857142857142857, 'recall': 0.10580204778156997}, 0.86: {'precision': 0.8867924528301887, 'recall': 0.08020477815699659}, 0.87: {'precision': 0.9069767441860465, 'recall': 0.06655290102389079}, 0.88: {'precision': 0.9142857142857143, 'recall': 0.05460750853242321}, 0.89: {'precision': 0.9310344827586207, 'recall': 0.04607508532423208}, 0.9: {'precision': 0.95, 'recall': 0.032423208191126277}, 0.91: {'precision': 0.9166666666666666, 'recall': 0.01877133105802048}, 0.92: {'precision': 0.8888888888888888, 'recall': 0.013651877133105802}, 0.93: {'precision': 1.0, 'recall': 0.010238907849829351}, 0.94: {'precision': 1.0, 'recall': 0.005119453924914676}, 0.95: {'precision': 1.0, 'recall': 0.0034129692832764505}, 0.96: {'precision': 1.0, 'recall': 0.0017064846416382253}, 0.97: {'precision': 0.0, 'recall': 0.0}, 0.98: {'precision': 0.0, 'recall': 0.0}, 0.99: {'precision': 0.0, 'recall': 0.0}}

In [14]:
from sklearn.model_selection import KFold, cross_val_score

df_copy = df_full_train.copy()
y_full_train = df_copy.pop('converted')
X_full_train = df_copy

kf = KFold(n_splits=5, shuffle=True, random_state=1)
auc_scores = []

for i, (train_idx, val_idx) in enumerate(kf.split(X_full_train, y_full_train)):
  X_train, y_train = X_full_train.iloc[train_idx], y_full_train.iloc[train_idx]
  X_val, y_val = X_full_train.iloc[val_idx], y_full_train.iloc[val_idx]
  vec = DictVectorizer(sparse=False)
  train_dict = X_train.to_dict(orient='records')
  val_dict = X_val.to_dict(orient='records')
  train_data = vec.fit_transform(train_dict)
  val_data = vec.transform(val_dict)
  df_train = pd.DataFrame(train_data, columns=vec.get_feature_names_out())
  df_val = pd.DataFrame(val_data, columns=vec.get_feature_names_out())
  model = LogisticRegression(solver='liblinear', C=1.0, max_iter=1000)
  model.fit(df_train, y_train)
  y_pred = model.predict(df_val)
  score = roc_auc_score(y_val, y_pred)
  auc_scores.append(score)

print(f"scores: {auc_scores}")
print(f"standard deviation: {np.std(auc_scores)}")

scores: [0.598298828438453, 0.5997560340281705, 0.6266218721037998, 0.6309138187696063, 0.628901405539479]
standard deviation: 0.014661887930321124

In [15]:
from numpy.typing import ArrayLike

def get_encoded_k_folds(X: ArrayLike, y: ArrayLike, k) -> tuple[list, list, list, list]:
  kf = KFold(n_splits=k, shuffle=True, random_state=1)
  train_fts, train_lbs, val_fts, val_lbs = [], [], [], []
  X = np.array(X)
  y = np.array(y)
  for i, (train_idx, val_idx) in enumerate(kf.split(X, y)):
    X_train, y_train = X_full_train.iloc[train_idx], y_full_train.iloc[train_idx]
    X_val, y_val = X_full_train.iloc[val_idx], y_full_train.iloc[val_idx]
    vec = DictVectorizer(sparse=False)
    train_dict = X_train.to_dict(orient='records')
    val_dict = X_val.to_dict(orient='records')
    train_data = vec.fit_transform(train_dict)
    val_data = vec.transform(val_dict)
    df_train = pd.DataFrame(train_data, columns=vec.get_feature_names_out())
    df_val = pd.DataFrame(val_data, columns=vec.get_feature_names_out())
    train_fts.append(df_train)
    train_lbs.append(y_train)
    val_fts.append(df_val)
    val_lbs.append(y_val)
  return train_fts, train_lbs, val_fts, val_lbs

In [16]:
df_copy = df_full_train.copy()
y_full_train = df_copy.pop('converted')
X_full_train = df_copy

c_vals = [0.000001, 0.001, 1, 3]
scores = {}

for c in c_vals:
  auc_scores = []
  train_fts, train_lbs, val_fts, val_lbs = get_encoded_k_folds(
      X_full_train, y_full_train, k=5)
  for X_train, y_train, X_val, y_val in zip(train_fts, train_lbs, val_fts, val_lbs):
    model = LogisticRegression(solver='liblinear', C=c, max_iter=1000)
    model.fit(X_train, y_train)
    y_pred = model.predict(X_val)
    score = roc_auc_score(y_val, y_pred)
    auc_scores.append(score)
  mean_auc = np.mean(auc_scores)
  std_auc = np.std(auc_scores)
  scores[c] = {"mean": round(mean_auc, 3), "std": round(std_auc, 3)}

print(scores)

{1e-06: {'mean': np.float64(0.504), 'std': np.float64(0.002)}, 0.001: {'mean': np.float64(0.608), 'std': np.float64(0.011)}, 1: {'mean': np.float64(0.617), 'std': np.float64(0.015)}, 3: {'mean': np.float64(0.617), 'std': np.float64(0.015)}}

In [17]:
def train(X_train, y_train, C=1.0):
  vec = DictVectorizer(sparse=False)
  train_dict = X_train.to_dict(orient='records')
  train_data = vec.fit_transform(train_dict)
  df_train = pd.DataFrame(train_data, columns=vec.get_feature_names_out())
  model = LogisticRegression(solver='liblinear', C=C, max_iter=1000)
  model.fit(df_train, y_train)
  return vec, model

def predict(X_test, vectorizer, model):
  test_dict = X_test.to_dict(orient='records')
  test_data = vectorizer.transform(test_dict)
  df_test = pd.DataFrame(test_data, columns=vectorizer.get_feature_names_out())
  y_pred = model.predict(df_test)
  return y_pred

### Final Model

In [20]:
C = 1

In [21]:
final_model = LogisticRegression(solver='liblinear', C=C, max_iter=1000)

df_train_copy = df_full_train.copy()
y_full_train = df_train_copy.pop('converted')
X_full_train = df_train_copy

df_test_copy = df_test.copy()
y_test = df_test_copy.pop('converted')
X_test = df_test_copy

vec, model = train(X_full_train, y_full_train, C=1)
y_pred = predict(X_test, vec, model)
score = roc_auc_score(y_test, y_pred)

print(score)

0.604264475743349

### Save the model

In [22]:
import pickle

In [26]:
output_file = f"model_C={C}.bin"
output_file

'model_C=1.bin'

In [27]:
with open(output_file, 'wb') as f_out:
  pickle.dump((vec, model), f_out)

print(f"successfully written file {output_file}")

successfully written file model_C=1.bin

### Load Model

In [1]:
import pickle

In [2]:
model_file = "model_C=1.bin"

with open(model_file, 'rb') as f_in:
  vec, model = pickle.load(f_in)

vec, model

(DictVectorizer(sparse=False),
 LogisticRegression(C=1, max_iter=1000, solver='liblinear'))

### Inference

In [3]:
customer = {
    'lead_source': 'organic_search',
    'industry': 'technology',
    'employment_status': 'employed',
    'location': 'europe',
    'annual_income': 88160.0,
    'number_of_courses_viewed': 3,
    'interaction_count': 4,
    'lead_score': 0.64
}

In [4]:
X = vec.transform([customer])
X

array([[8.816e+04, 0.000e+00, 1.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 4.000e+00, 6.400e-01, 0.000e+00, 0.000e+00, 1.000e+00,
        0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00,
        1.000e+00, 0.000e+00, 0.000e+00, 3.000e+00]])

In [5]:
model.predict(X)

/opt/conda/envs/ml-zoomcamp/lib/python3.11/site-packages/sklearn/utils/validation.py:2830: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(

array([1])